# Generated by Django 5.0 on 2023-12-25 09:06

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_account_balance_account_balance_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default=None, editable=False, max_length=3),
        ),
    ]
