# Generated by Django 5.0 on 2023-12-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_account_balance_alter_account_balance_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='descruotuib',
            field=models.TextField(null=True),
        ),
    ]
