# Generated by Django 5.0 on 2023-12-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_transaction_descruotuib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='descruotuib',
            new_name='description',
        ),
    ]
