# Generated by Django 5.0 on 2023-12-25 09:14

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_rename_descruotuib_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='EUR', max_digits=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='EUR', max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
    ]
