# Generated by Django 5.0 on 2023-12-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_alter_transaction_accounting_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='description',
            new_name='long_description',
        ),
    ]
