# Generated by Django 5.0 on 2023-12-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_rename_description_transaction_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
