# Generated by Django 5.0 on 2024-04-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsV2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='productsV2.product')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsV2.property')),
            ],
            options={
                'unique_together': {('product', 'property')},
            },
        ),
    ]
