# Generated by Django 5.0 on 2024-04-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsV2', '0002_alter_property_options_productproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='default_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsV2.propertyvalue'),
        ),
    ]
