# Generated by Django 5.0 on 2024-04-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsV2', '0003_productproperty_default_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name_plural': 'product properties'},
        ),
        migrations.DeleteModel(
            name='ProductPropertyValue',
        ),
    ]
