# Generated by Django 5.0 on 2024-03-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_attribute_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributedefinition',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
