# Generated by Django 5.0 on 2024-03-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattributedefinition_read_only'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
    ]
