# Generated by Django 5.0 on 2024-03-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productattributedefinition_possible_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='value',
            new_name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
    ]
