# Generated by Django 5.0 on 2023-12-25 08:32

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_credit_limit_customer_credit_limit_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
