# Generated by Django 5.0 on 2023-12-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='credit_limit',
            new_name='legact_credit_limit',
        ),
    ]
