# Generated by Django 5.0 on 2024-01-01 08:15

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_credit_limit_company_legact_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='credit_limit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='credit_limit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3, null=True),
        ),
    ]
