# Generated by Django 5.0 on 2024-01-01 08:15

from django.db import migrations
from djmoney.money import Money


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_address_postal_code_company_credit_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="legact_credit_limit",
        ),
    ]
